/* Generated by scripts/fetch-s13-assets.cjs — do not edit. Riot Games assets, see README. */
export interface S13Asset { readonly kind: 'champion' | 'trait' | 'item'; readonly id: string; readonly path: string; readonly source: string; readonly bytes: number; readonly sha256: string }
export const S13_ASSET_PATCH = '14.24';
export const S13_ASSETS: readonly S13Asset[] = [];
