/* Generated by scripts/fetch-s13-assets.cjs — do not edit. Riot Games assets, see README. */
export interface S13Asset { readonly kind: 'champion' | 'trait' | 'item'; readonly id: string; readonly path: string; readonly source: string; readonly bytes: number; readonly sha256: string }
export const S13_ASSET_PATCH = '14.24';
export const S13_ASSETS: readonly S13Asset[] = [
  {
    "kind": "champion",
    "id": "irelia",
    "path": "assets/s13/champions/irelia.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_irelia/hud/tft13_irelia_square.tft_set13.png",
    "bytes": 25944,
    "sha256": "dbb4536e2116e1f72e2f241eaa30efd2a59d323a7f6144606077488dbdcb35ad"
  },
  {
    "kind": "champion",
    "id": "maddie",
    "path": "assets/s13/champions/maddie.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_shooter/hud/tft13_shooter_square.tft_set13.png",
    "bytes": 22360,
    "sha256": "7bf031a32a73be2189d2de5a220a542c1dd04c89f30c3fa40d194cb676dcfdc8"
  },
  {
    "kind": "champion",
    "id": "darius",
    "path": "assets/s13/champions/darius.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_darius/hud/tft13_darius_square.tft_set13.png",
    "bytes": 24352,
    "sha256": "8f144afc7dfa08aaa7c275ecb545ffcbd9d160135a88441f9aface6085bdbfbe"
  },
  {
    "kind": "champion",
    "id": "lux",
    "path": "assets/s13/champions/lux.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_lux/hud/tft13_lux_square.tft_set13.png",
    "bytes": 23020,
    "sha256": "7434af8b6ce7fada72b620adab3c8b0a92eb5638fb6d97edd884ec4a83f483ba"
  },
  {
    "kind": "champion",
    "id": "zyra",
    "path": "assets/s13/champions/zyra.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_zyra/hud/tft13_zyra_square.tft_set13.png",
    "bytes": 23277,
    "sha256": "2d2729f7d10edadfbc84b60750025c836c00a3f04c4b26a3ca8d81d85738c037"
  },
  {
    "kind": "champion",
    "id": "tristana",
    "path": "assets/s13/champions/tristana.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_tristana/hud/tft13_tristana_square.tft_set13.png",
    "bytes": 24485,
    "sha256": "8711e710b1efec94a880dec1f3f7e7cd8c7bedb829cdec46c108d18cc6a0e20e"
  },
  {
    "kind": "champion",
    "id": "urgot",
    "path": "assets/s13/champions/urgot.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_urgot/hud/tft13_urgot_square.tft_set13.png",
    "bytes": 23776,
    "sha256": "0d072a1227887f114e68ebac15297d1c669897d8dc62e8021e8a020413e601f9"
  },
  {
    "kind": "champion",
    "id": "rell",
    "path": "assets/s13/champions/rell.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_rell/hud/tft13_rell_square.tft_set13.png",
    "bytes": 25980,
    "sha256": "039d1f8e3a7e9bfaaa5436771e3df351f9a3412a25b078016bbd26c722df4a9d"
  },
  {
    "kind": "champion",
    "id": "leona",
    "path": "assets/s13/champions/leona.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_leona/hud/tft13_leona_square.tft_set13.png",
    "bytes": 25870,
    "sha256": "6189d496987a51288e405f33ecb279e9deb7576583fd550b6fd38443919ac84f"
  },
  {
    "kind": "champion",
    "id": "vander",
    "path": "assets/s13/champions/vander.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_prime/hud/tft13_prime_square.tft_set13.png",
    "bytes": 20403,
    "sha256": "4cd4547fc863b1f481bdb936f019a1c18072bff4c5140d44c3e77c9f25a0682a"
  },
  {
    "kind": "champion",
    "id": "kogmaw",
    "path": "assets/s13/champions/kogmaw.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_kogmaw/hud/tft13_kogmaw_square.tft_set13.png",
    "bytes": 24684,
    "sha256": "54632ba89e0e035ed5f785caca0dd04ea026390fa29906f9adbd4493562d01aa"
  },
  {
    "kind": "champion",
    "id": "scar",
    "path": "assets/s13/champions/scar.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_flyguy/hud/tft13_flyguy_square.tft_set13.png",
    "bytes": 22579,
    "sha256": "d0d938a69eed87201de60b4bb4c5877d3d2cb9cda50f1f4e883269cb5ca73d75"
  },
  {
    "kind": "champion",
    "id": "ezreal",
    "path": "assets/s13/champions/ezreal.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_ezreal/hud/tft13_ezreal_square.tft_set13.png",
    "bytes": 24696,
    "sha256": "8a6785eb80058498c425d9174b73d4110b6e0e61a8d0f7d5f404316e8f206c4e"
  },
  {
    "kind": "champion",
    "id": "loris",
    "path": "assets/s13/champions/loris.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_beardy/hud/tft13_beardy_square.tft_set13.png",
    "bytes": 23426,
    "sha256": "f4c8ed57183ae04025be3be2533738931014db92b5b6b5b6ccb81ae9664c9c66"
  },
  {
    "kind": "champion",
    "id": "nami",
    "path": "assets/s13/champions/nami.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_nami/hud/tft13_nami_square.tft_set13.png",
    "bytes": 25758,
    "sha256": "3369e7d376b32a8ca5f73bc699ecffd1f1fc7aa0de32998113bd0051c4af11a8"
  },
  {
    "kind": "champion",
    "id": "corki",
    "path": "assets/s13/champions/corki.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_corki/hud/tft13_corki_square.tft_set13.png",
    "bytes": 26016,
    "sha256": "2de6c4044c928f3f206c4a99d40d29c7e15c0947ea1d4fbd4f5b815fb848fff6"
  },
  {
    "kind": "champion",
    "id": "garen",
    "path": "assets/s13/champions/garen.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_garen/hud/tft13_garen_square.tft_set13.png",
    "bytes": 24472,
    "sha256": "b37f8ae796304cbda1a47b76772f7b44e4c6aa19849c483bf0c025f33b407e08"
  },
  {
    "kind": "champion",
    "id": "zoe",
    "path": "assets/s13/champions/zoe.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_zoe/hud/tft13_zoe_square.tft_set13.png",
    "bytes": 22202,
    "sha256": "99948fa86ba326fb264303139e2e8f221dc7d764bde37978c31c016b2aa5213e"
  },
  {
    "kind": "champion",
    "id": "caitlyn",
    "path": "assets/s13/champions/caitlyn.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/characters/tft13_caitlyn/hud/tft13_caitlyn_square.tft_set13.png",
    "bytes": 21661,
    "sha256": "abfa09b160aeee6295bf5f42901eea37c1d7209fb95b8f0a6649878239b86b73"
  },
  {
    "kind": "trait",
    "id": "TFT13_Sorcerer",
    "path": "assets/s13/traits/TFT13_Sorcerer.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/ux/traiticons/trait_icon_3_sorcerer.png",
    "bytes": 524,
    "sha256": "dcc69e29f96b8e197eefb2de26015fbf259c6d14652a6693e87b362b16d899c9"
  },
  {
    "kind": "trait",
    "id": "TFT13_Martialist",
    "path": "assets/s13/traits/TFT13_Martialist.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/ux/traiticons/trait_icon_13_artillerist.tft_set13.png",
    "bytes": 368,
    "sha256": "744a020922253695aeb2436e6679c6f95a3f68b88ffc7855e4082947491510d7"
  },
  {
    "kind": "trait",
    "id": "TFT13_Titan",
    "path": "assets/s13/traits/TFT13_Titan.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/ux/traiticons/trait_icon_10_warden.png",
    "bytes": 448,
    "sha256": "940e0a1b85120eb27254e652f7072569a1dcdbfbb4dc7f89ba41a725b1cde7bc"
  },
  {
    "kind": "trait",
    "id": "TFT13_Sniper",
    "path": "assets/s13/traits/TFT13_Sniper.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/ux/traiticons/trait_icon_6_sniper.png",
    "bytes": 637,
    "sha256": "defb5ffd06359fcc672ebf0085b37f90e4de81a500260dd6e14cba2c0266caea"
  },
  {
    "kind": "trait",
    "id": "TFT13_Watcher",
    "path": "assets/s13/traits/TFT13_Watcher.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/ux/traiticons/trait_icon_13_watcher.tft_set13.png",
    "bytes": 370,
    "sha256": "9b8eee935673fc971e5fba18516191481bddf14be0d161b2b8fd1fb6be6cff6b"
  },
  {
    "kind": "item",
    "id": "sword",
    "path": "assets/s13/items/sword.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_bfsword.tft_set13.png",
    "bytes": 18426,
    "sha256": "b84723913cbeafed158b6bad6a370ca87d0147d3cbb07edeec5dc6080d7514ac"
  },
  {
    "kind": "item",
    "id": "bow",
    "path": "assets/s13/items/bow.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_recurvebow.tft_set13.png",
    "bytes": 16982,
    "sha256": "847ab5d93b186ee656ca48669fecd0c289a631a3c8a5b3175e5595f317dea3b2"
  },
  {
    "kind": "item",
    "id": "rod",
    "path": "assets/s13/items/rod.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_needlesslylargerod.tft_set13.png",
    "bytes": 22182,
    "sha256": "7ea14e098939ef5fa9a0e60c30485f83c258e3f91cd9a4ad45137224af483364"
  },
  {
    "kind": "item",
    "id": "tear",
    "path": "assets/s13/items/tear.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_tearofthegoddess.tft_set13.png",
    "bytes": 15827,
    "sha256": "088e955d26146772cd95273554bcbd58cee28ac6c50e044c574e4121725978f7"
  },
  {
    "kind": "item",
    "id": "vest",
    "path": "assets/s13/items/vest.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_chainvest.tft_set13.png",
    "bytes": 17561,
    "sha256": "b98dd2e3e19c5c278c81ee6174c64d6bf7fc3106e334f5af94de780064a8bfce"
  },
  {
    "kind": "item",
    "id": "cloak",
    "path": "assets/s13/items/cloak.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_negatroncloak.tft_set13.png",
    "bytes": 21315,
    "sha256": "21ae8f1d8b45baf30e068d408b52e268e7a180e1f517bd30001731cd734fd94b"
  },
  {
    "kind": "item",
    "id": "belt",
    "path": "assets/s13/items/belt.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_giantsbelt.tft_set13.png",
    "bytes": 18233,
    "sha256": "8b921cd3fe04f5e526096a0701f40fe71a1a7d1ca36e8157a997023f6400e7a9"
  },
  {
    "kind": "item",
    "id": "rageblade",
    "path": "assets/s13/items/rageblade.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_guinsoosrageblade.tft_set13.png",
    "bytes": 19689,
    "sha256": "771624630c945e068e12aa090c8b8479b893c0d459353009710cb65a780d99cc"
  },
  {
    "kind": "item",
    "id": "deathblade",
    "path": "assets/s13/items/deathblade.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_deathblade.tft_set13.png",
    "bytes": 18508,
    "sha256": "b1b8d4503da7ae0797c4a8e28577ca36c34437d1791b1040470ae1a1cb007018"
  },
  {
    "kind": "item",
    "id": "shojin",
    "path": "assets/s13/items/shojin.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_spearofshojin.tft_set13.png",
    "bytes": 19586,
    "sha256": "c309fbf39033b53d718d0052178d3e2c8613791083e6502e3d70290c0b782bd8"
  },
  {
    "kind": "item",
    "id": "archangel",
    "path": "assets/s13/items/archangel.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_archangelsstaff.tft_set13.png",
    "bytes": 19362,
    "sha256": "36cef8f64c1e169bd512461db1fb41fb269f8853da9b4d2cf1fb60638c1be32d"
  },
  {
    "kind": "item",
    "id": "deathcap",
    "path": "assets/s13/items/deathcap.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_rabadonsdeathcap.tft_set13.png",
    "bytes": 22158,
    "sha256": "d6843a1b08168988f53bbc6a11919ee461ea25649649334ae8cb657dce85d142"
  },
  {
    "kind": "item",
    "id": "warmog",
    "path": "assets/s13/items/warmog.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_warmogsarmor.tft_set13.png",
    "bytes": 25296,
    "sha256": "0131e1ac31099ddf776bb4dd02ac7cf04050f520849cd88fab7e8a9dd9f77b38"
  },
  {
    "kind": "item",
    "id": "dragons-claw",
    "path": "assets/s13/items/dragons-claw.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_dragonsclaw.tft_set13.png",
    "bytes": 19316,
    "sha256": "b60a7144c4789f400840c8d9aac55c1e43394beb0960b94a393b1cc3c488d341"
  },
  {
    "kind": "item",
    "id": "gargoyle",
    "path": "assets/s13/items/gargoyle.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_gargoylestoneplate.tft_set13.png",
    "bytes": 20423,
    "sha256": "e0415c612ec42909e6138f651f4a99290008bff6706d89d4c61384e4db6dd624"
  },
  {
    "kind": "item",
    "id": "gunblade",
    "path": "assets/s13/items/gunblade.png",
    "source": "https://raw.communitydragon.org/14.24/game/assets/maps/tft/icons/items/hexcore/tft_item_hextechgunblade.tft_set13.png",
    "bytes": 23051,
    "sha256": "d824cb0a7eae2142a6c06ffeb9572302ffd4042d6e0bde2c8b1caf1fa22e752d"
  }
];
