/** Finite S13 engine constants and semantic identifiers are part of the content
 * digest. A change here invalidates earlier development saves and goldens. */
export const S13_COMBAT_RULES = Object.freeze({
  tickMs: 50,
  maxTicks: 1200,
  moveIntervalTicks: 5,
  abilityPowerBase: 100,
  attackCritBps: 2500,
  critMultiplierBps: 14000,
  attackMana: 10,
  damageManaBps: 300,
  damageManaCap: 20,
  attackSpeedIntervalNumerator: 2000000000,
  starStatPercent: Object.freeze([100, 180, 324]),
  arithmeticRevision: 'm8-b3-g04-g05-g06-g07-1',
  modifierPipeline: 'm8-global-numeric-01-bigint-intermediates-safe-integer-results',
  damagePipeline: 'm8-g02-delivery-permissions-true-bypass-inherited-single-mitigation',
  spellCriticalStrikes: 'm8-g03-authorized-per-packet-actor-action-target-ordinal-word-threshold',
  neutralAttackTiming: 'authored-integer-ticks-no-speed-inversion',
  attackSpeedStacking: 'original-base-times-sum-static-runtime-status-final-ceil',
  packetOrder: 'owner-action-target-ordinal',
  statusTiming: 'new-action-status-next-tick-full-duration',
  periodicTiming: 'final-before-expiry-ordinary-before-actions-per-task-effect-target-rational-remainders',
  statusStacking: 'same-instance-refresh-independent-instances-strongest-retains-suppressed-burn-clock-only',
  healingPipeline: 'exact-merge-once-wound-cap-three-stage-largest-remainder-source-shares',
  shieldPipeline: 'initial-linear-decay-distinct-from-absorption-end-consumed-once',
  survivalPipeline: 'whole-batch-positive-damage-surviving-hp-and-maxhp-frozen-before-effects',
  anomalySampling: 'one-word-full-range-scale-exclude-last',
  emptyAnomaly: 'defer-until-purchase-preserve-affordable-offer',
  damageSharing: 'all-hit-packets-including-mitigated-ricochet-one-transfer-no-recursion',
  ricochet: 'primary-lethal-only-once-per-action-no-redirect-no-recursion',
});
