/** E-owned expectations: literal independent arithmetic, never generated by the aggregator. */
import { describe, expect, it } from 'vitest';
import type { CombatEvent, CombatOrigin } from '../src/simulation/combat-types';
import { aggregateStats, appendStats, emptyStats } from '../src/stats/aggregate';

const origin = (ownerId: string): CombatOrigin => ({ ownerId, sourceKind: 'ability', definitionId: 'oracle-ability', instanceId: 'oracle', effectIndex: 0 });
function events(data: readonly CombatEvent[]): CombatEvent[] {
  return data.map((event, eventSeq) => ({ ...event, domain: 'combat', combatId: 'round-1', eventSeq }));
}
function packet(unitId: string, hpDamage: number, absorbed: number, overrides: Partial<Extract<CombatEvent, { type: 'packetDamage' }>> = {}): CombatEvent {
  return { type: 'packetDamage', tick: 1, source: origin('attacker'), unitId, damageType: 'physical', raw: hpDamage + absorbed,
    mitigated: hpDamage + absorbed, absorbed, hpDamage, actionSeq: 0, packetOrdinal: 0, critical: false, redirected: false, ...overrides };
}
const row = (unitId: string, hpDamage = 0, physicalHpDamage = 0, magicHpDamage = 0, shieldAbsorbed = 0, effectiveHealing = 0, overhealing = 0) =>
  ({ unitId, hpDamage, physicalHpDamage, magicHpDamage, shieldAbsorbed, effectiveHealing, overhealing });
const relevantRows = (result: ReturnType<typeof aggregateStats>) => [...result.units].sort((a, b) => a.unitId.localeCompare(b.unitId));

describe('M6 independent stats oracle (E)', () => {
  it('475 split 238/237 with shields100/200 gives HP175 and received shield300 exactly once', () => {
    const ledger = events([
      packet('target', 138, 100, { raw: 238, mitigated: 238 }),
      packet('loris', 37, 200, { raw: 237, mitigated: 237, redirected: true, packetOrdinal: 1 }),
      { type: 'damage', tick: 1, unitId: 'target', amount: 238, hp: 862, physicalAmount: 238, magicAmount: 0, absorbed: 100, hpDamage: 138, shield: 0 },
      { type: 'damage', tick: 1, unitId: 'loris', amount: 237, hp: 963, physicalAmount: 237, magicAmount: 0, absorbed: 200, hpDamage: 37, shield: 0 },
    ]);
    expect(relevantRows(aggregateStats('run-a', 'round-1', ledger))).toEqual([
      row('attacker', 175, 175), row('loris', 0, 0, 0, 200), row('target', 0, 0, 0, 100),
    ]);
  });
  it('requested100 with30 missing credits effective30 and overheal70 to healer, not patient', () => {
    const ledger = events([{ type: 'heal', tick: 1, unitId: 'patient', source: origin('healer'), requested: 100, actual: 30, overheal: 70, hp: 100 }]);
    const result = aggregateStats('run-a', 'round-1', ledger);
    expect(result.units.find(unit => unit.unitId === 'healer')).toEqual(row('healer', 0, 0, 0, 0, 30, 70));
    expect(result.units.find(unit => unit.unitId === 'patient')?.effectiveHealing ?? 0).toBe(0);
  });
  it('same tick physical and magic hits count actual HP, including overkill capped at remaining7', () => {
    const ledger = events([
      packet('victim', 11, 0),
      packet('victim', 7, 0, { damageType: 'magic', raw: 100, mitigated: 100, packetOrdinal: 1 }),
      { type: 'kill', tick: 1, unitId: 'victim', source: origin('attacker') },
      { type: 'death', tick: 1, unitId: 'victim' },
    ]);
    const result = aggregateStats('run-a', 'round-1', ledger);
    expect(result.units.find(unit => unit.unitId === 'attacker')).toEqual(row('attacker', 18, 11, 7));
  });
  it('multiple shield layers absorbed20+30 credit50; granting500 never becomes absorption', () => {
    const layer = { key: 's1', source: origin('shielder'), granted: 500, remaining: 480, absorbed: 20, expiresAtTick: 20 };
    const ledger = events([
      { type: 'shieldLayerChanged', tick: 0, unitId: 'target', layer: { ...layer, remaining: 500, absorbed: 0 }, reason: 'granted' },
      { type: 'shieldLayerChanged', tick: 1, unitId: 'target', layer, reason: 'absorbed' },
      { type: 'shieldLayerChanged', tick: 1, unitId: 'target', layer: { ...layer, key: 's2', remaining: 0, absorbed: 30 }, reason: 'absorbed' },
      packet('target', 9, 50, { raw: 59, mitigated: 59 }),
    ]);
    const result = aggregateStats('run-a', 'round-1', ledger);
    expect(result.units.find(unit => unit.unitId === 'target')).toEqual(row('target', 0, 0, 0, 50));
    expect(result.units.find(unit => unit.unitId === 'attacker')).toEqual(row('attacker', 9, 9));
    expect(result.units.find(unit => unit.unitId === 'shielder')?.shieldAbsorbed ?? 0).toBe(0);
  });
  it('dead/sold historical source retains damage attribution and incremental boundaries do not duplicate', () => {
    const ledger = events([
      { type: 'death', tick: 1, unitId: 'sold-source' },
      packet('victim', 25, 5, { tick: 2, source: origin('sold-source'), damageType: 'magic' }),
      packet('victim', 8, 0, { tick: 2, source: origin('sold-source'), damageType: 'magic', packetOrdinal: 1 }),
    ]);
    const first = appendStats(emptyStats('run-a', 'round-1'), ledger.slice(0, 2));
    const before = structuredClone(first);
    const final = appendStats(first, ledger.slice(2));
    expect(first).toEqual(before);
    expect(final.nextEventSeq).toBe(3);
    expect(final.units.find(unit => unit.unitId === 'sold-source')).toEqual(row('sold-source', 33, 0, 33));
    expect(final.units.find(unit => unit.unitId === 'victim')).toEqual(row('victim', 0, 0, 0, 5));
    expect(() => appendStats(final, ledger.slice(2))).toThrow();
    expect(() => appendStats(emptyStats('run-a', 'round-1'), ledger.slice(1))).toThrow();
    expect(() => aggregateStats('run-a', 'round-2', ledger)).toThrow();
  });
  it('pause/seek rebuild uses only selected verified prefix, leaving original totals unchanged', () => {
    const ledger = events([packet('target', 10, 0), packet('target', 20, 0), packet('target', 30, 0)]);
    const full = aggregateStats('run-a', 'round-1', ledger);
    const rewind = aggregateStats('run-a', 'round-1', ledger.slice(0, 1));
    expect(rewind.units.find(unit => unit.unitId === 'attacker')?.hpDamage).toBe(10);
    expect(full.units.find(unit => unit.unitId === 'attacker')?.hpDamage).toBe(60);
    expect(appendStats(rewind, ledger.slice(1)).units.find(unit => unit.unitId === 'attacker')?.hpDamage).toBe(60);
  });
});
