/* F1 prototype only: immutable archive/seek load measurement against accepted domain. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const {run}=require('./generate-m5-route.cjs'),{hash}=require('./m4-evidence.cjs'),{sourceFingerprint}=require('./m5-evidence.cjs');
const bytes=x=>Buffer.byteLength(JSON.stringify(x));
const measure=f=>{const t=performance.now();const value=f();return {ms:performance.now()-t,value};};
const summary=a=>{a=[...a].sort((a,b)=>a-b);return {count:a.length,p50:a[Math.floor(a.length*.5)],p95:a[Math.min(a.length-1,Math.floor(a.length*.95))],max:a.at(-1)};};
(async()=>{const {createServer}=await import('vite');const server=await createServer({root:path.resolve(__dirname,'..'),server:{middlewareMode:true,ws:false},optimizeDeps:{noDiscovery:true,include:[]},appType:'custom'});const report={stage:'F1 prototype, not production validation',sha:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),dirty:execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(),sourceFingerprint:sourceFingerprint(),node:process.version,cpu:os.cpus()[0].model,cpuCount:os.cpus().length,memoryBytes:os.totalmem(),startedAt:new Date().toISOString(),routes:[],passed:false};
try{const api=await server.ssrLoadModule('/src/simulation/match.ts'),ser=await server.ssrLoadModule('/src/simulation/serialization.ts');
for(const build of ['cannon','sniper','mage','sniper-caitlyn']){const started=performance.now(),route=await run(api,{build,seed:42,retainStates:true});assert.equal(route.rounds.length,30);assert.equal(route.final.outcome,'victory');const battles=[];const restores=[],replays=[],seeks=[],captures=[];let maxTickBatchMs=0;
for(const r of route.rounds){const context=ser.restoreMatch(r.before),start=api.startMatchCombat(context);assert(start.ok);const events=[...start.events.filter(e=>e.domain==='combat')];let state=start.state;const checkpoints=[{tick:0,state,seq:events.length}];const t=performance.now();while(state.phase==='combat'){const step=api.stepMatch(state);state=step.state;events.push(...step.events.filter(e=>e.domain==='combat'));if(state.combat.tick%40===0)checkpoints.push({tick:state.combat.tick,state,seq:events.length});}replays.push(performance.now()-t);assert.deepEqual(events,r.events.filter(e=>e.domain==='combat'));assert.deepEqual(state,r.after);const capture=measure(()=>structuredClone({context,initial:start.state.combat,events,terminal:state.combat}));captures.push(capture.ms);
const restore=measure(()=>ser.restoreMatch(start.state));restores.push(restore.ms);
for(const target of [...new Set([0,Math.floor(state.combat.tick/2),Math.max(0,state.combat.tick-1),state.combat.tick])]){const cp=checkpoints.filter(c=>c.tick<=target).at(-1);const seek=measure(()=>{let s=ser.restoreMatch(cp.state);const seen=[];while(s.combat.tick<target&&s.phase==='combat'){const next=api.stepMatch(s);s=next.state;seen.push(...next.events.filter(e=>e.domain==='combat'));}assert.deepEqual(seen,events.slice(cp.seq,cp.seq+seen.length));return s;});seeks.push(seek.ms);maxTickBatchMs=Math.max(maxTickBatchMs,seek.ms);}
battles.push({runId:`f1-${build}`,combatId:state.combat.combatId,context,initial:start.state.combat,events,endTick:state.combat.tick,nextEventSeq:state.combat.nextEventSeq,result:state.combat.result,stateHash:hash(state.combat),eventHash:hash(events)});}
const payload={kind:'hex-autobattler-save',saveFormatVersion:1,replayFormatVersion:1,runId:`f1-${build}`,match:route.final,battles,currentBattle:null,createdAt:'2026-10-06T00:00:00.000Z'};const validate=measure(()=>{ser.restoreMatch(payload.match);for(const battle of battles)ser.restoreMatch(battle.context);});const serial=measure(()=>JSON.stringify(payload));const parse=measure(()=>JSON.parse(serial.value));const row={build,seed:42,combatCount:30,round:35,payloadBytes:bytes(payload),events:battles.reduce((n,b)=>n+b.events.length,0),maxBattleEvents:Math.max(...battles.map(b=>b.events.length)),maxBattleBytes:Math.max(...battles.map(bytes)),maxBattleTicks:Math.max(...battles.map(b=>b.endTick)),maxBoard:Math.max(...battles.map(b=>b.context.preparation.units.filter(u=>u.team==='player'&&u.location.kind==='board').length)),maxItems:Math.max(...battles.map(b=>b.context.items.length)),maxEquippedItems:Math.max(...battles.map(b=>b.context.items.filter(i=>i.location.kind==='unit').length)),captureMs:summary(captures),restoreMs:summary(restores),fullBattleReplayMs:summary(replays),cached40TickSeekMs:summary(seeks),fullHistoryReplayMs:replays.reduce((n,x)=>n+x,0),contextValidateMs:validate.ms,jsonStringifyMs:serial.ms,jsonParseMs:parse.ms,elapsedMs:performance.now()-started};report.routes.push(row);console.log(JSON.stringify(row));fs.writeFileSync(`work/m6-f1-${build}.json`,serial.value);if(build==='cannon')fs.writeFileSync('work/m6-f1-payload.json',serial.value);
// A legal population stress branch from the actual last pre-battle state. Every change is a command.
if(build==='cannon'){let state=ser.restoreMatch(route.rounds.at(-1).before);const commands=[];function accept(name,args){const next=api[name](state,...args);if(!next.ok)return false;state=next.state;commands.push({name,args});return true;}
while(state.level<9&&accept('buyXp',[])){}let attempts=0;while(state.preparation.units.filter(u=>u.team==='player').length<18&&attempts++<100){let bought=false;for(let slot=0;slot<5;slot++)if(accept('buyUnit',[slot,state.shop.generation]))bought=true;if(!accept('rerollShop',[]))break;}
for(const unit of state.preparation.units.filter(u=>u.team==='player'&&u.location.kind==='bench')){if(state.preparation.units.filter(u=>u.team==='player'&&u.location.kind==='board').length>=9)break;let done=false;for(let row=4;row<8&&!done;row++)for(let col=0;col<7&&!done;col++)if(!state.preparation.units.some(u=>u.location.kind==='board'&&u.location.cell.col===col&&u.location.cell.row===row))done=accept('deployMatchUnit',[unit.id,{kind:'board',cell:{col,row}}]);}
for(const item of state.items.filter(i=>i.location.kind==='inventory')){let done=false;for(const unit of state.preparation.units.filter(u=>u.team==='player'&&u.location.kind==='board'))for(let slot=0;slot<3&&!done;slot++)done=accept('equipItem',[item.id,unit.id,slot]);}
ser.restoreMatch(state);const before=state;const step=api.startMatchCombat(state);assert(step.ok);state=step.state;const events=[...step.events.filter(e=>e.domain==='combat')];const t=performance.now();while(state.phase==='combat'){const next=api.stepMatch(state);state=next.state;events.push(...next.events.filter(e=>e.domain==='combat'));}ser.restoreMatch(state);report.populationStress={source:'cannon seed42 round35 pre-battle; only accepted commands',commands,level:before.level,board:before.preparation.units.filter(u=>u.team==='player'&&u.location.kind==='board').length,bench:before.preparation.units.filter(u=>u.team==='player'&&u.location.kind==='bench').length,items:before.items.length,equipped:before.items.filter(i=>i.location.kind==='unit').length,events:events.length,ticks:state.combat.tick,bytes:bytes({context:before,initial:step.state.combat,events,terminal:state.combat}),replayMs:performance.now()-t};fs.writeFileSync('work/m6-f1-population.json',JSON.stringify({before,after:state,events,commands}));console.log(JSON.stringify(report.populationStress));}
}
report.threeCompletedArchiveBytes=report.routes.slice(0,3).reduce((n,r)=>n+r.payloadBytes,0);report.peakProcessRssBytes=process.resourceUsage().maxRSS*1024;assert.equal(sourceFingerprint(),report.sourceFingerprint);report.passed=true;
}finally{report.endedAt=new Date().toISOString();report.finalSourceFingerprint=sourceFingerprint();fs.writeFileSync('docs/evidence/M6_F1_LOAD.json',JSON.stringify(report,null,2));await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
